version: "3"
networks:
  reunionou.net:
    driver: bridge
services:
  #################
  # AUTH SERVICES #
  #################
  api.auth:
    image: "canals/php:latest"
    environment:
      - VHOST_HOSTNAME=api.auth.reunionou
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "49380:80"
      - "49344:443"
    volumes:
      - "./reunionou/auth_service:/var/www"
    working_dir: /var/www/src
    networks:
      - reunionou.net
    depends_on:
      - auth.db

  auth.db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root
    ports:
      - "49317:27017"
    networks:
      - reunionou.net
  ##################
  # EVENT SERVICES #
  ##################
  api.event:
    image: "canals/php:latest"
    environment:
      - VHOST_HOSTNAME=api.event.reunionou
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "49381:80"
      - "49345:443"
    volumes:
      - "./reunionou/event_service:/var/www"
    working_dir: /var/www/src
    networks:
      - reunionou.net
    depends_on:
      - event.db

  event.db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root
    ports:
      - "49318:27017"
    networks:
      - reunionou.net
