version: "3"
networks:
  reunionou.net:
    driver: bridge
services:
  ###################
  # GLOBAL COMPOSER #
  ###################
  composer:
    image: composer/composer
    networks:
      - reunionou.net
    volumes:
      - "./reunionou/composer:/composer"
      - "./reunionou/composer/vendor:/var/www/vendor"
    container_name: composer
    working_dir: /composer
    command: install
    # environment:
    #   - HTTP_PROXY=http://www-cache.iutnc.univ-lorraine.fr:3128/
    #   - HTTPS_PROXY=http://www-cache.iutnc.univ-lorraine.fr:3128/
  #################
  # AUTH SERVICES #
  #################
  api.auth:
    image: "canals/php:latest"
    environment:
      - VHOST_HOSTNAME=api.auth.reunionou
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "49380:80"
      - "49344:443"
    volumes:
      - "./reunionou/auth_service:/var/www"
      - "./reunionou/composer/vendor:/var/www/vendor"
    working_dir: /var/www/src
    networks:
      reunionou.net:
        aliases:
          - api.auth.reunionou
    depends_on:
      - auth.db

  auth.db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root
    ports:
      - "49317:27017"
    networks:
      - reunionou.net
  ##################
  # EVENT SERVICES #
  ##################
  api.event:
    image: "canals/php:latest"
    environment:
      - VHOST_HOSTNAME=api.event.reunionou
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "49381:80"
      - "49345:443"
    volumes:
      - "./reunionou/event_service:/var/www"
      - "./reunionou/composer/vendor:/var/www/vendor"
    working_dir: /var/www/src
    networks:
      reunionou.net:
        aliases:
          - api.event.reunionou
    depends_on:
      - event.db

  event.db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root
    ports:
      - "49318:27017"
    networks:
      - reunionou.net
  ##################
  # COMMENT SERVICES #
  ##################
  api.comment:
    image: "canals/php:latest"
    environment:
      - VHOST_HOSTNAME=api.comment.reunionou
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "49382:80"
      - "49346:443"
    volumes:
      - "./reunionou/comment_service:/var/www"
      - "./reunionou/composer/vendor:/var/www/vendor"
    working_dir: /var/www/src
    networks:
      reunionou.net:
        aliases:
          - api.comment.reunionou
    depends_on:
      - comment.db

  comment.db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root
    ports:
      - "49319:27017"
    networks:
      - reunionou.net
    ##################
  # GATEWAY WEBAPP #
  ##################
  api.frontoffice:
    image: "canals/php:latest"
    environment:
      - VHOST_HOSTNAME=api.frontoffice.reunionou
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "49383:80"
      - "49311:443"
    volumes:
      - "./reunionou/front_office_webapp:/var/www"
      - "./reunionou/composer/vendor:/var/www/vendor"
    working_dir: /var/www/src
    networks:
      - reunionou.net
    depends_on:
      - api.auth
